# Site settings
title: Milan Sobat
email: milansobatblog@gmail.com
description: "All things to do with functional fitness; structural integrity, stretching, weightlifting, active recovery, routines, etc."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
